### ISSUE TITLE
Support more number formats in Bus Compare component

### ISSUE THREAD

**Issue by edstott** [tomcl/issie#222]
**Is your feature request related to a problem? Please describe.**
Constants can be defined using multiple number formats. Bus Compare component only accepts decimal input. When the value is entered, the sheet shows it in hexadecimal format, which is inconsistent

**Describe the solution you'd like**
Allow the 'Compare With' parameter of Bus Compare to be specified in decimal (including signed), hex or binary

**Comment by tomcl** [comment]
Yes! This was not done because doing it for constants was painful, requiring a lot of implementation changes as well as a component type change. The main pain is because it is necessary then to store the text creating the number as well as the number. The dialog functions were not initially created to do this.

**Comment by tomcl** [comment]
The way to do this is:
(1) abstract the code currently implementing constant into one or more functions that will work for bus compare
(2) make sure constant still works
(3) implement bus compare similarly
