### ISSUE TITLE
Modern wire circles placed in wrong position

### ISSUE THREAD

**Issue by tomcl** [tomcl/issie#348]
Bug:

When two wires are identical for first few segments (as below) the displayed circle showing where the two wires join should be located at the point that they diverge, However it is created at a different point as in the example below.

![2023-08-07 18_35_15-issie](https://github.com/tomcl/issie/assets/7545073/cd1a8bfa-8233-40cf-a66d-9d1f62c4d87a)

v4.0.a.8 and earlier.

All platforms.

**Comment by Luk3dley** [comment]
Can I get assigned this issue please?

**Comment by tomcl** [comment]
The code is in the render logic in BusWire. You need to understand the way that segments in a wire are represented:

Unfortunately I cannot find good documentation of the Wire datatype. I'm sure we used to have it.

I've just added some info to

https://chat.openai.com/share/4141eef7-cd2f-454c-a29e-859d9cbffea7

It is now (just) adequate.

**Comment by Luk3dley** [comment]
I believe the issue is that when the IntersectOrJumpList is created, because the two wires overlap it generates the intersection at the beginning of the wire instead of where they branch. I've implemented a temporary fix using an if statement for when the Intersect offset is at the start of the wire,
![Fig 1](https://github.com/tomcl/issie/assets/37420114/4ef092d3-993b-4c67-8bab-fff6b0df332a)
![Fig 2](https://github.com/tomcl/issie/assets/37420114/3038bc39-5290-44f2-9e07-856693c40344)

 however this introduces issues when the wire is manually dragged to the beginning of the wire.
![Fig 3](https://github.com/tomcl/issie/assets/37420114/ca3f8ec4-2bde-43ff-a5d6-cad2c2722920)
(also for some reason it now generates 3 circles (2 overlapping) if slightly offset from 0???)
![Fig 4](https://github.com/tomcl/issie/assets/37420114/050af01a-9dcf-401a-8aed-ad6cacc19e70)

The only solutions I have come up with are that either the code for the IntersectOrJumpList generation will need to be changed to account for this case, or limit how far along a wire can be manually dragged to prevent this from happening (I'm looking into the former)

**Comment by tomcl** [comment]
You need to examine a whole net (all non-zero segments of) , and add circles only when there is a T junction, which would rule out the spurious circle.

You need to filter possible circles.

for a circle to be valid you need a T junction: 3 segments in 3 different directions with same endpoint or two segments - one vertical and one horizontal, with endpoint of one in middle of other.

There are zero length segments - you need to deal with them to avoid anomalies.

There are many ways through this. If you detect possible circles points first and then filter looking at all net segments it should not be too inefficient.

**Comment by Luk3dley** [comment]
Turns out I was going about this completely wrong - The problem was in the vJoinCircles function in BusWireUpdateHelpers. The function returned [hs.Qmin, hs.Index, hs.OfWire] in line 708, when it should have returned [join.P, hs.Index, hs.OfWire]. Changing this passes all the tests I've put it through, such as rotating, scaling and moving wires manually.
![Screenshot_1](https://github.com/tomcl/issie/assets/37420114/4596eaf2-bd5f-4499-aa5b-54b9b4329fcd)

**Comment by tomcl** [comment]
Luc, has this been PRed - shall I close it?

**Comment by Luk3dley** [comment]
I'm away for a month and don't have access to a computer so haven't been able to submit a pr yet, but once I'm back (24th) I'll put it through

**Comment by tomcl** [comment]
Closed by #420
