### ISSUE TITLE
Improving Waveform Simulator performance

### ISSUE THREAD

**Issue by tomcl** [tomcl/issie#465]
**Is your feature request related to a problem? Please describe.**
The waveform simulator does not scroll well with very large designs and high numbers of waveforms

**Describe the solution you'd like**
In this state waveform generation should be delayed and batched

**Additional context**

* Currently waveform SVGs are generated on-demand - and if generation takes a long time this is split into multiple GenerateWaveform messages.
* Waveforms are generated from update function (e.g. scrollbar mouse updates), not view function. In addition multiple mouse moves will lead to multiple updates.
* Three possible solutions: 
   * Batch mouse move updates
   * Move waveform generation to the view function which is "batched" anyway
   * As above, but check WaveSim state and delay waveform generation if there are scrollbar move updates pending.

**Key problem**

Elmish does not give us easy control over the message queue and concurrency. We cannot even query the queue to determine the number of messages awaiting execution. The workaround for this is as follows:

1. When a mouse move is received by update function store it in a local queue, **and send a mouse move handshake message**. Do not change the rets of the model.
2. When a mouse move handshake message is received check whether its original move is still in the queue.
   1. If original is in queue, release **the whole queue**, coalescing all moves in the queue - which means acting on only the latest move. 
   2. If original is not in queue discard the handshake doing nothing. We can be sure that eventually the correct handshake will be received.

Thus when the message queue is full multiple moves will get batched and released by the (delayed) handshake from the first one. When it is empty each handshake will happen immediately, and moves get acted on with no delay.

**Additional Requirements**

1. When a queued move is received it would be good to update the waveform **clock cycle row** immediately. This is always fast. In addition the values column can be updated - if the scrolling causes the cursor to move. This is also fast. So in step 1. above we could allow the model to be changed for the scrolled view, but **delay all of the waveform generation** until step 3.
2. If the mouse is clicked on some part of the scrollbar which is NOT the thumb maybe that should result in an immediate move to that location. Not sure about this? It might be surprising when clicking on a very small thumb and missing it.
3. Implement non-linear move translation so that moving small distances precisely is easy. Not sure this is easy to make intuitive, so perhaps it cannot be done.

**Comment by samuelpswang** [comment]
**Key Problem**

Upon further investigation of the source code submitted in #456, it was found that the batching of mouse movements was already included. The mechanism of the batching operation is described below, in case this issue needs to be further discussed:

1. When a mouse event is detected on the scrollbar SVGs, a `ScrollbarMouseMsg` tagged with a `ScrollbarMouseAction` type is put into the Elmish queue via the `dispatch` function. _Note that these messages contains all possible values of the `ScrollbarMouseAction` EXCEPT the `ReleaseScrollQueue` value. See the `makeScrollbar` function in Renderer/UI/WaveSim/WaveSimNavigation.fs._
2. These events are caught by the `update` function in Renderer/UI/Update.fs, which executes the `updateScrollbar` function in Renderer/UI/WaveSim/WaveSimNavigation.fs. Here only the `InScrollbarDrag` value is of concern, since we want to execute `StartScrollbarDrag` and `ClearScrollbarDrag` immediately.
3. When a `InScrollbarDrag` message is received by `updateScrollbar`:
    * step 1: it checks if there are any `InScrollbarDrag` message pending as recorded by `WaveSimModel.ScrollbarQueueIsEmpty`;
    * step 2: it updates the `WaveSimModel` with the current message, and set `WaveSimModel.ScrollbarQueueIsEmpty` to false (in `setScrollbarLastX`);
    * step 3: if `WaveSimModel.ScrollbarQueueIsEmpty` is true when we checked in step 1, then further `ScrollbarMouseMsg` with `ReleaseScrollQueue` action is dispatched.
4. When a `ReleaseScrollQueue` message is received by `updateScrollbar`, it updates the view of the wave simulator, and sets the `WaveSimModel.ScrollbarQueueIsEmpty` to `false` when it is done.

The above described mechanism can ensure that there is only one `ReleaseScrollQueue` message in the Elmish queue at any point in time, effectively batching the `InScrollbarDrag` messages when the Elmish queue is full and a `ReleaseScrollQueue` message is not executed immediately.

**Additional Requirements**

Provided additional requirements for this issue needs further discussion and more accurate specifications. Main comments are listed below:

1. Delaying waveform SVG: events within Elmish queue seems to be resolved faster than they are dispatched usually, with the delay seen currently mainly as a result of the on-demand generation of SVGs, which meant that we are likely to be stuck in a continuous loop of -- user moves mouse -> generating SVGs -> user moves mouse again due to empty wave window -- to do this we need to pin down the frequency of SVG generation.
2. Jump to location: possible, should attempt at further point in time.
3. Non-linear move translation: possible, tried but was not intuitive, requires more experimentation.

**Final Comments**

Closing this issue for now, as the main performance boost recommendation was completed.
