### ISSUE TITLE
Unable to Access or Display Memory Addresses Beyond 0x10 When Address Width is Greater

### ISSUE THREAD

**Issue by LH-and-FPGA** [tomcl/issie#495]
## Describe the bug  
When the `number of elements` is a memory component is greater than `16`, memory addresses beyond `0x10` cannot be accessed or displayed properly. We cannot modify them as well. The number of memory locations displayed is limited, which prevents accessing higher addresses.

## To Reproduce  
1. Set the memory address width to a value greater than `4`.
2. Try to use `View/Edit memory content` function.
3. Observe that addresses greater than `0x10` are not accessible or displayed.

## Expected behavior  
I expected that when the address is increased beyond `0x10`, the system should allow access to and display all memory addresses, with no limit on the number of memory locations displayed.

## Desktop:
- OS: `Windows 11`
- Version: `v5.2.2`

## Screenshot
![屏幕截图 2024-12-16 122605](https://github.com/user-attachments/assets/44b3048d-cfbc-4c5a-83a2-1ee2a8e5fa82)

**Comment by tomcl** [comment]
I am not sure I understand this.

- Take the Erastoshenes demo (v5.2.2, Windows)
- Go to either ROM or RAM on top-level sheet and select properties
- Change the "First location to view or change" box to say 0x200
- Memory locations from 0x200 - 0x210 are displayed

Is there some bug that occurs under different conditions? Or maybe a MacOs -only bug?

More generally this UI is interesting:

- It is easy for users not to see the "first location to view or change" box. I hope this, and its function, is well-enough flagged now?
- We could have another box determining how many locations are displayed - but that is maybe more complexity than worth it?
- We could have a larger number of memory locations displayed - 16 is a bit small and scrolling is fine and much easier than changing the box.

I'd be happy to make the number of locations a compile-time constant and change it to default 64, if that would help. I am not sure more complexity is needed here because it is not very useful looking an RAM/ROM init contents in properties. ROM contants are normally generated by another program - e.g. eepassembler. But maybe there are use cases i'm not considering?

**Comment by LH-and-FPGA** [comment]
The "First Location To View and Change" option above is indeed useful, but I was wondering if presenting all the content in a paginated format might make it more convenient to view? Additionally, it might be helpful to include an option to adjust the length of content displayed on each page. This could be particularly useful when working with Asynchronous ROM, as it would allow for quicker comparison and editing of content.

**Comment by tomcl** [comment]
**I was wondering if presenting all the content in a paginated format might make it more convenient to view?**
One challenge is that we need to display content of any width in any radix. In fact now that memories can have a width of up to 2^16 (or so) this is very challenging and not met by the current code. I'd rather keep things simple and have some graceful way to manage very wide memories. But the current display is pretty basic and could be improved.

Note that I have (juts this Summer) improved the run-time diaply of RAMs and ROMs.

**Additionally, it might be helpful to include an option to adjust the length of content displayed on each page. This could be particularly useful when working with Asynchronous ROM, as it would allow for quicker comparison and editing of content.**
Yes, I agree - see discussion above.

The most useful extension of current code is quite complex: a table-driven general purpose disassembler in which arbitrary assembly code could be displayed a field values converted to mnemonics by providing a run-time setup file. You would want to keep this simple and I think not allow more than single-word decoding. That would work for EEP1 well enough.

**Comment by LH-and-FPGA** [comment]
I understand now, thank you!
