### ISSUE TITLE
Copy pasting creates items with matching names, causing an error

### ISSUE THREAD

**Issue by pclemow** [tomcl/issie#64]
Pretty self-explanatory. When you copy-paste a block, it inherits the name, guaranteeing an error when trying to use the simulator/waveform.

**Comment by tomcl** [comment]
true, but v easy to work around since the click / properties way of changing names is very fast, and duplicates are efficiently highlighted by the simulation error checks.

Not too difficult to do properly, and it would be useful for complex logic, so I'll put this on the list for future dev when more important things are done.

**Comment by tomcl** [comment]
fixed v2.0.0
